## Importar librerías

In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
url='https://data.cityofnewyork.us/resource/h9gi-nx95.csv'

In [3]:
df=pd.read_csv(url)

In [4]:
df.sample(5)

,crash_date,crash_time,borough,zip_code,latitude,longitude,location,on_street_name,off_street_name,cross_street_name,...,contributing_factor_vehicle_2,contributing_factor_vehicle_3,contributing_factor_vehicle_4,contributing_factor_vehicle_5,collision_id,vehicle_type_code1,vehicle_type_code2,vehicle_type_code_3,vehicle_type_code_4,vehicle_type_code_5
785,2019-10-02T00:00:00.000,14:11,NaN,NaN,40.740093,-73.899860,POINT (-73.89986 40.740093),BROOKLYN QUEENS EXPRESSWAY,NaN,NaN,...,Unsafe Lane Changing,NaN,NaN,NaN,4217011,Sedan,Sedan,NaN,NaN,NaN
234,2019-10-08T00:00:00.000,7:20,BROOKLYN,11205.0,40.694576,-73.956150,POINT (-73.95615 40.694576),BEDFORD AVENUE,MYRTLE AVENUE,NaN,...,Unspecified,Unspecified,NaN,NaN,4222962,Motorcycle,Station Wagon/Sport Utility Vehicle,Station Wagon/Sport Utility Vehicle,NaN,NaN
167,2019-10-08T00:00:00.000,23:30,QUEENS,11427.0,40.726707,-73.747520,POINT (-73.74752 40.726707),89 AVENUE,216 STREET,NaN,...,Unspecified,NaN,NaN,NaN,4220282,Sedan,NaN,NaN,NaN,NaN
315,2019-10-19T00:00:00.000,20:50,NaN,NaN,40.639576,-73.998146,POINT (-73.998146 40.639576),48 STREET,NaN,NaN,...,Unspecified,Unspecified,NaN,NaN,4227318,Station Wagon/Sport Utility Vehicle,Sedan,Sedan,NaN,NaN
508,2019-10-11T00:00:00.000,16:30,NaN,NaN,40.748512,-73.988720,POINT (-73.98872 40.748512),AVENUE OF THE AMERICAS,NaN,NaN,...,Passing or Lane Usage Improper,NaN,NaN,NaN,4222206,Taxi,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN

In [5]:
df.dtypes

crash_date                        object
crash_time                        object
borough                           object
zip_code                         float64
latitude                         float64
longitude                        float64
location                          object
on_street_name                    object
off_street_name                   object
cross_street_name                 object
number_of_persons_injured          int64
number_of_persons_killed           int64
number_of_pedestrians_injured      int64
number_of_pedestrians_killed       int64
number_of_cyclist_injured          int64
number_of_cyclist_killed           int64
number_of_motorist_injured         int64
number_of_motorist_killed          int64
contributing_factor_vehicle_1     object
contributing_factor_vehicle_2     object
contributing_factor_vehicle_3     object
contributing_factor_vehicle_4     object
contributing_factor_vehicle_5     object
collision_id                       int64
vehicle_type_code1                object
vehicle_type_code2                object
vehicle_type_code_3               object
vehicle_type_code_4               object
vehicle_type_code_5               object
dtype: object

¿Cómo sé el largo del df (número de filas)?

In [6]:
df.shape

(1000, 29)

In [7]:
len(df)

1000

Me insteresa saber si hay filas con NaN

In [8]:
df.isna().sum()

crash_date                         0
crash_time                         0
borough                          380
zip_code                         380
latitude                         100
longitude                        100
location                         100
on_street_name                   218
off_street_name                  509
cross_street_name                782
number_of_persons_injured          0
number_of_persons_killed           0
number_of_pedestrians_injured      0
number_of_pedestrians_killed       0
number_of_cyclist_injured          0
number_of_cyclist_killed           0
number_of_motorist_injured         0
number_of_motorist_killed          0
contributing_factor_vehicle_1      6
contributing_factor_vehicle_2    135
contributing_factor_vehicle_3    939
contributing_factor_vehicle_4    977
contributing_factor_vehicle_5    993
collision_id                       0
vehicle_type_code1                 7
vehicle_type_code2               188
vehicle_type_code_3              941
vehicle_type_code_4              977
vehicle_type_code_5              993
dtype: int64

¿Cómo me aseguro que los _collision_id_ son únicos?

In [9]:
df['collision_id'].nunique()

1000

### Trabajo con filtro

In [10]:
df['borough'].value_counts()

QUEENS           213
BROOKLYN         183
MANHATTAN        114
BRONX             97
STATEN ISLAND     13
Name: borough, dtype: int64

Para filtrar solo _QUEENS_

1) opción "filtro largo"

In [11]:
df[df['borough']=='QUEENS']

,crash_date,crash_time,borough,zip_code,latitude,longitude,location,on_street_name,off_street_name,cross_street_name,...,contributing_factor_vehicle_2,contributing_factor_vehicle_3,contributing_factor_vehicle_4,contributing_factor_vehicle_5,collision_id,vehicle_type_code1,vehicle_type_code2,vehicle_type_code_3,vehicle_type_code_4,vehicle_type_code_5
0,2019-10-21T00:00:00.000,9:30,QUEENS,11416.0,40.683453,-73.855606,POINT (-73.855606 40.683453),ROCKAWAY BOULEVARD,97 AVENUE,NaN,...,Unspecified,NaN,NaN,NaN,4226874,Station Wagon/Sport Utility Vehicle,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN
9,2019-10-24T00:00:00.000,7:05,QUEENS,11375.0,40.715073,-73.827220,POINT (-73.82722 40.715073),126 STREET,UNION TURNPIKE,NaN,...,Driver Inattention/Distraction,NaN,NaN,NaN,4228591,Sedan,Pick-up Truck,NaN,NaN,NaN
10,2019-10-22T00:00:00.000,17:00,QUEENS,11423.0,40.720352,-73.763240,POINT (-73.76324 40.720352),NaN,NaN,198-63 FOOTHILL AVENUE,...,NaN,NaN,NaN,NaN,4227760,Sedan,NaN,NaN,NaN,NaN
11,2019-10-18T00:00:00.000,14:20,QUEENS,11385.0,40.695070,-73.903160,POINT (-73.90316 40.69507),NaN,NaN,1060 WYCKOFF AVENUE,...,NaN,NaN,NaN,NaN,4225875,Box Truck,NaN,NaN,NaN,NaN
13,2019-10-16T00:00:00.000,18:45,QUEENS,11422.0,40.665245,-73.737090,POINT (-73.73709 40.665245),140 AVENUE,SOUTH CONDUIT AVENUE,NaN,...,Unspecified,NaN,NaN,NaN,4224224,Sedan,Bus,NaN,NaN,NaN
18,2019-10-04T00:00:00.000,0:33,QUEENS,11433.0,40.699990,-73.783900,POINT (-73.7839 40.69999),NaN,NaN,107-09 172 STREET,...,Unspecified,NaN,NaN,NaN,4219444,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN,NaN
28,2019-10-09T00:00:00.000,17:38,QUEENS,11432.0,40.714542,-73.781240,POINT (-73.78124 40.714542),AVON STREET,WEXFORD TERRACE,NaN,...,Unspecified,NaN,NaN,NaN,4220543,Motorcycle,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN
33,2019-10-18T00:00:00.000,16:54,QUEENS,11419.0,40.684383,-73.823265,POINT (-73.823265 40.684383),107 AVENUE,LEFFERTS BOULEVARD,NaN,...,Unspecified,NaN,NaN,NaN,4226733,Sedan,NaN,NaN,NaN,NaN
36,2019-10-04T00:00:00.000,8:16,QUEENS,11418.0,40.704680,-73.835900,POINT (-73.8359 40.70468),NaN,NaN,83-67 116 STREET,...,Unspecified,NaN,NaN,NaN,4217685,Bus,Sedan,NaN,NaN,NaN
37,2019-10-04T00:00:00.000,19:41,QUEENS,11420.0,40.682537,-73.807160,POINT (-73.80716 40.682537),LINDEN BOULEVARD,135 STREET,NaN,...,Unspecified,NaN,NaN,NaN,4217706,Sedan,Taxi,NaN,NaN,NaN
39,2019-10-22T00:00:00.000,2:12,QUEENS,11412.0,40.691210,-73.752960,POINT (-73.75296 40.69121),119 AVENUE,198 STREET,NaN,...,Unspecified,NaN,NaN,NaN,4227583,Sedan,Sedan,NaN,NaN,NaN
45,2019-10-30T00:00:00.000,8:00,QUEENS,11354.0,40.766075,-73.831240,POINT (-73.83124 40.766075),NaN,NaN,34-25 LINDEN PLACE,...,Unspecified,NaN,NaN,NaN,4232174,Sedan,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN
51,2019-10-02T00:00:00.000,14:00,QUEENS,11366.0,40.732830,-73.782875,POINT (-73.782875 40.73283),NaN,NaN,73-11 188 STREET,...,Unspecified,NaN,NaN,NaN,4216484,Sedan,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN
53,2019-10-03T00:00:00.000,12:30,QUEENS,11375.0,40.724400,-73.849810,POINT (-73.84981 40.7244),QUEENS BOULEVARD,68 DRIVE,NaN,...,Unspecified,NaN,NaN,NaN,4217118,Sedan,Bus,NaN,NaN,NaN
54,2019-10-03T00:00:00.000,16:20,QUEENS,11435.0,40.698917,-73.806900,POINT (-73.8069 40.698917),NaN,NaN,94-06 SUTPHIN BOULEVARD,...,Unspecified,NaN,NaN,NaN,4217132,Station Wagon/Sport Utility Vehicle,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN
60,2019-10-28T00:00:00.000,14:00,QUEENS,11422.0,40.667220,-73.737050,POINT (-73.73705 40.66722),NaN,NaN,138-69 FRANCIS LEWIS BOULEVARD,...,Unspecified,NaN,NaN,NaN,4231094,Box Truck,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN
69,2019-10-02T00:00:00.000,11:18,QUEENS,11434.0,40.666637,-73.781490,POINT (-73.78149 40.666637),155 STREET,SOUTH CONDUIT AVENUE,NaN,...,Unspecified,NaN,NaN,NaN,4216996,Station Wagon/Sport Utility Vehicle,Sedan,NaN,NaN,NaN
74,2019-10-30T00:00:00.000,16:42,QUEENS,11374.0,40.719975,-73.865240,POINT (-73.86524 40.719975),WOODHAVEN BOULEVARD,65 AVENUE,NaN,...,Driver Inattention/Distraction,NaN,NaN,NaN,4232278,Sedan,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN
94,2019-10-16T00:00:00.000,19:00,QUEENS,11368.0,40.740585,-73.858536,POINT (-73.858536 40.740585),NaN,NaN,54-23 102 STREET,...,Unspecified,NaN,NaN,NaN,4224348,Sedan,NaN,NaN,NaN,NaN
96,2019-10-17T00:00:00.000,11:00,QUEENS,11363.0,40.771034,-73.739130,POINT (-73.73913 40.771034),NaN,NaN,41-82 LITTLE NECK PARKWAY,...,Unspecified,NaN,NaN,NaN,4224754,Station Wagon/Sport Utility Vehicle,Sedan,NaN,NaN,NaN
97,2019-10-07T00:00:00.000,13:00,QUEENS,11374.0,40.711597,-73.858190,POINT (-73.85819 40.711597),METROPOLITAN AVENUE,TROTTING COURSE LANE,NaN,...,Unspecified,NaN,NaN,NaN,4219420,Station Wagon/Sport Utility Vehicle,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN
99,2019-10-22T00:00:00.000,18:00,QUEENS,11362.0,40.761690,-73.732830,POINT (-73.73283 40.76169),MARATHON PARKWAY,THORNHILL AVENUE,NaN,...,NaN,NaN,NaN,NaN,4227636,Sedan,NaN,NaN,NaN,NaN
100,2019-10-13T00:00:00.000,5:00,QUEENS,11422.0,40.659390,-73.737210,POINT (-73.73721 40.65939),144 AVENUE,249 STREET,NaN,...,Unspecified,Unspecified,Unspecified,NaN,4222213,Sedan,Sedan,Sedan,Sedan,NaN
113,2019-10-22T00:00:00.000,20:15,QUEENS,11421.0,40.691810,-73.851190,POINT (-73.85119 40.69181),WOODHAVEN BOULEVARD,88 ROAD,NaN,...,Unspecified,NaN,NaN,NaN,4227752,Sedan,Sedan,NaN,NaN,NaN
119,2019-10-14T00:00:00.000,20:55,QUEENS,11378.0,40.721030,-73.904106,POINT (-73.904106 40.72103),FLUSHING AVENUE,61 STREET,NaN,...,Unspecified,NaN,NaN,NaN,4223388,Sedan,Sedan,NaN,NaN,NaN
120,2019-10-04T00:00:00.000,18:55,QUEENS,11368.0,40.750225,-73.855150,POINT (-73.85515 40.750225),111 STREET,42 AVENUE,NaN,...,NaN,NaN,NaN,NaN,4218612,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN,NaN
130,2019-10-04T00:00:00.000,9:00,QUEENS,11434.0,40.667370,-73.782660,POINT (-73.78266 40.66737),NORTH CONDUIT AVENUE,CRANSTON STREET,NaN,...,Unspecified,NaN,NaN,NaN,4218063,Sedan,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN
145,2019-10-04T00:00:00.000,10:35,QUEENS,11434.0,40.673008,-73.788090,POINT (-73.78809 40.673008),150 STREET,ROCKAWAY BOULEVARD,NaN,...,Unspecified,NaN,NaN,NaN,4218067,Station Wagon/Sport Utility Vehicle,Sedan,NaN,NaN,NaN
150,2019-10-10T00:00:00.000,17:30,QUEENS,11101.0,40.744800,-73.953415,POINT (-73.953415 40.7448),VERNON BOULEVARD,47 ROAD,NaN,...,Unspecified,NaN,NaN,NaN,4221138,Station Wagon/Sport Utility Vehicle,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN
156,2019-10-25T00:00:00.000,10:05,QUEENS,11375.0,40.732944,-73.847015,POINT (-73.847015 40.732944),110 STREET,64 ROAD,NaN,...,Failure to Yield Right-of-Way,NaN,NaN,NaN,4229329,Station Wagon/Sport Utility Vehicle,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
841,2019-10-07T00:00:00.000,14:00,QUEENS,11411.0,40.692104,-73.742730,POINT (-73.74273 40.692104),119 AVENUE,219 STREET,NaN,...,Unspecified,NaN,NaN,NaN,4219357,Sedan,Sedan,NaN,NaN,NaN
843,2019-10-23T00:00:00.000,16:20,QUEENS,11427.0,40.723640,-73.755775,POINT (-73.755775 40.72364),HILLSIDE AVENUE,211 STREET,NaN,...,Unspecified,NaN,NaN,NaN,4228288,Sedan,Chassis Cab,NaN,NaN,NaN
854,2019-10-27T00:00:00.000,11:30,QUEENS,11412.0,40.693360,-73.752070,POINT (-73.75207 40.69336),118 AVENUE,200 STREET,NaN,...,NaN,NaN,NaN,NaN,4230848,Sedan,NaN,NaN,NaN,NaN
858,2019-10-20T00:00:00.000,15:15,QUEENS,11385.0,40.704697,-73.863060,POINT (-73.86306 40.704697),NaN,NaN,78-56 86 STREET,...,Unspecified,NaN,NaN,NaN,4226853,Sedan,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN
861,2019-10-10T00:00:00.000,0:00,QUEENS,11411.0,40.697830,-73.729620,POINT (-73.72962 40.69783),115 AVENUE,229 STREET,NaN,...,Unspecified,NaN,NaN,NaN,4221140,Sedan,Sedan,NaN,NaN,NaN
868,2019-10-16T00:00:00.000,17:00,QUEENS,11004.0,40.736214,-73.713486,POINT (-73.713486 40.736214),NaN,NaN,254-20 HILLSIDE AVENUE,...,Unspecified,NaN,NaN,NaN,4224381,Sedan,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN
872,2019-10-05T00:00:00.000,11:30,QUEENS,11428.0,40.721590,-73.731020,POINT (-73.73102 40.72159),JAMAICA AVENUE,224 STREET,NaN,...,NaN,NaN,NaN,NaN,4217950,Sedan,NaN,NaN,NaN,NaN
880,2019-10-25T00:00:00.000,11:00,QUEENS,11432.0,40.712685,-73.783710,POINT (-73.78371 40.712685),NaN,NaN,179-15 HILLSIDE AVENUE,...,Unspecified,Unspecified,Unspecified,NaN,4229269,Sedan,Sedan,Station Wagon/Sport Utility Vehicle,Sedan,NaN
884,2019-10-04T00:00:00.000,17:20,QUEENS,11378.0,40.725918,-73.895350,POINT (-73.89535 40.725918),GRAND AVENUE,69 STREET,NaN,...,Failure to Yield Right-of-Way,NaN,NaN,NaN,4218233,Station Wagon/Sport Utility Vehicle,Sedan,NaN,NaN,NaN
897,2019-10-04T00:00:00.000,14:49,QUEENS,11385.0,40.709682,-73.898910,POINT (-73.89891 40.709682),LINDEN STREET,FRESH POND ROAD,NaN,...,Unspecified,NaN,NaN,NaN,4218239,Station Wagon/Sport Utility Vehicle,Pick-up Truck,NaN,NaN,NaN
899,2019-10-09T00:00:00.000,8:57,QUEENS,11426.0,40.741650,-73.716576,POINT (-73.716576 40.74165),LITTLE NECK PARKWAY,81 AVENUE,NaN,...,Unspecified,NaN,NaN,NaN,4220353,Station Wagon/Sport Utility Vehicle,Bus,NaN,NaN,NaN
901,2019-10-22T00:00:00.000,16:00,QUEENS,11429.0,40.715626,-73.741394,POINT (-73.741394 40.715626),217 STREET,100 AVENUE,NaN,...,Unspecified,Unspecified,NaN,NaN,4228019,Sedan,Sedan,Station Wagon/Sport Utility Vehicle,NaN,NaN
902,2019-10-03T00:00:00.000,17:30,QUEENS,11101.0,40.750187,-73.950160,POINT (-73.95016 40.750187),NaN,NaN,10-25 44 AVENUE,...,Unspecified,NaN,NaN,NaN,4217221,Pick-up Truck,Sedan,NaN,NaN,NaN
903,2019-10-26T00:00:00.000,3:02,QUEENS,11435.0,40.694065,-73.801420,POINT (-73.80142 40.694065),SUTPHIN BOULEVARD,107 AVENUE,NaN,...,Unspecified,NaN,NaN,NaN,4239074,Sedan,Sedan,NaN,NaN,NaN
907,2019-10-28T00:00:00.000,8:00,QUEENS,11432.0,40.711823,-73.787860,POINT (-73.78786 40.711823),HILLSIDE AVENUE,175 STREET,NaN,...,Unspecified,NaN,NaN,NaN,4231048,Bus,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN
910,2019-10-06T00:00:00.000,3:49,QUEENS,11385.0,40.696740,-73.900510,POINT (-73.90051 40.69674),CYPRESS AVENUE,SUMMERFIELD AVENUE,NaN,...,Unspecified,NaN,NaN,NaN,4218276,Station Wagon/Sport Utility Vehicle,Box Truck,NaN,NaN,NaN
915,2019-10-21T00:00:00.000,8:50,QUEENS,11419.0,40.687668,-73.811700,POINT (-73.8117 40.687668),107 AVENUE,133 STREET,NaN,...,Failure to Yield Right-of-Way,NaN,NaN,NaN,4227249,Station Wagon/Sport Utility Vehicle,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN
918,2019-10-12T00:00:00.000,1:00,QUEENS,11429.0,40.705223,-73.746260,POINT (-73.74626 40.705223),NaN,NaN,209-31 112 AVENUE,...,Unspecified,NaN,NaN,NaN,4221790,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN,NaN
920,2019-10-03T00:00:00.000,21:00,QUEENS,11422.0,40.678417,-73.729225,POINT (-73.729225 40.678417),BROOKVILLE BOULEVARD,130 AVENUE,NaN,...,Unspecified,NaN,NaN,NaN,4217259,Sedan,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN
943,2019-10-05T00:00:00.000,16:30,QUEENS,11378.0,40.722600,-73.904570,POINT (-73.90457 40.7226),61 STREET,57 ROAD,NaN,...,Unspecified,NaN,NaN,NaN,4218270,Sedan,Sedan,NaN,NaN,NaN
951,2019-10-13T00:00:00.000,20:00,QUEENS,11426.0,40.725950,-73.721480,POINT (-73.72148 40.72595),91 AVENUE,247 STREET,NaN,...,Unspecified,NaN,NaN,NaN,4223213,Station Wagon/Sport Utility Vehicle,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN
953,2019-10-25T00:00:00.000,16:35,QUEENS,11692.0,40.597660,-73.785410,POINT (-73.78541 40.59766),NaN,NaN,54-81 ALMEDA AVENUE,...,Unspecified,NaN,NaN,NaN,4233109,Sedan,NaN,NaN,NaN,NaN
955,2019-10-22T00:00:00.000,19:00,QUEENS,11361.0,40.768826,-73.763620,POINT (-73.76362 40.768826),221 STREET,37 AVENUE,NaN,...,Passing or Lane Usage Improper,NaN,NaN,NaN,4227658,Station Wagon/Sport Utility Vehicle,Sedan,NaN,NaN,NaN
957,2019-10-04T00:00:00.000,6:00,QUEENS,11356.0,40.785660,-73.855095,POINT (-73.855095 40.78566),14 AVENUE,112 STREET,NaN,...,Unspecified,NaN,NaN,NaN,4220901,Sedan,NaN,NaN,NaN,NaN
959,2019-10-07T00:00:00.000,7:44,QUEENS,11417.0,40.676395,-73.850900,POINT (-73.8509 40.676395),NaN,NaN,109-08 86 STREET,...,Unspecified,NaN,NaN,NaN,4219372,Sedan,Bus,NaN,NaN,NaN
969,2019-10-11T00:00:00.000,14:00,QUEENS,11004.0,40.752777,-73.707430,POINT (-73.70743 40.752777),NaN,NaN,269-01 76 AVENUE,...,NaN,NaN,NaN,NaN,4221718,Sedan,NaN,NaN,NaN,NaN
972,2019-10-11T00:00:00.000,19:48,QUEENS,11414.0,40.667900,-73.842040,POINT (-73.84204 40.6679),CROSS BAY BOULEVARD,153 AVENUE,NaN,...,Unspecified,NaN,NaN,NaN,4221679,Bike,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN
992,2019-10-10T00:00:00.000,8:00,QUEENS,11412.0,40.701412,-73.768390,POINT (-73.76839 40.701412),HANNIBAL STREET,HILBURN AVENUE,NaN,...,Unspecified,NaN,NaN,NaN,4220935,Sedan,Sedan,NaN,NaN,NaN
994,2019-10-25T00:00:00.000,18:36,QUEENS,11385.0,40.700512,-73.899124,POINT (-73.899124 40.700512),MYRTLE AVENUE,STEPHEN STREET,NaN,...,Unspecified,NaN,NaN,NaN,4230594,Pick-up Truck,NaN,NaN,NaN,NaN
998,2019-10-30T00:00:00.000,8:23,QUEENS,11368.0,40.747740,-73.857750,POINT (-73.85775 40.74774),NaN,NaN,107-98 45 AVENUE,...,Unspecified,NaN,NaN,NaN,4232379,Station Wagon/Sport Utility Vehicle,Ambulance,NaN,NaN,NaN

supongamos que quiero la columna fecha y ubicación de Queens

In [12]:
df.loc[df['borough']=='QUEENS',['crash_date','location']].head(2)

                crash_date                      location
0  2019-10-21T00:00:00.000  POINT (-73.855606 40.683453)
9  2019-10-24T00:00:00.000   POINT (-73.82722 40.715073)

2da forma: usar una condición, definida como **variable**

In [13]:
condicion_1=df['borough']=='QUEENS'

In [14]:
df[condicion_1].head(2)

,crash_date,crash_time,borough,zip_code,latitude,longitude,location,on_street_name,off_street_name,cross_street_name,...,contributing_factor_vehicle_2,contributing_factor_vehicle_3,contributing_factor_vehicle_4,contributing_factor_vehicle_5,collision_id,vehicle_type_code1,vehicle_type_code2,vehicle_type_code_3,vehicle_type_code_4,vehicle_type_code_5
0,2019-10-21T00:00:00.000,9:30,QUEENS,11416.0,40.683453,-73.855606,POINT (-73.855606 40.683453),ROCKAWAY BOULEVARD,97 AVENUE,NaN,...,Unspecified,NaN,NaN,NaN,4226874,Station Wagon/Sport Utility Vehicle,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN
9,2019-10-24T00:00:00.000,7:05,QUEENS,11375.0,40.715073,-73.827220,POINT (-73.82722 40.715073),126 STREET,UNION TURNPIKE,NaN,...,Driver Inattention/Distraction,NaN,NaN,NaN,4228591,Sedan,Pick-up Truck,NaN,NaN,NaN

Supongamos que quiero ahora dos condiciones

In [15]:
condicion_2=df['borough']=='BRONX'

¿Cómo filtro los casos que son de Queens **o** del bronx

In [16]:
df[condicion_1|condicion_2]

,crash_date,crash_time,borough,zip_code,latitude,longitude,location,on_street_name,off_street_name,cross_street_name,...,contributing_factor_vehicle_2,contributing_factor_vehicle_3,contributing_factor_vehicle_4,contributing_factor_vehicle_5,collision_id,vehicle_type_code1,vehicle_type_code2,vehicle_type_code_3,vehicle_type_code_4,vehicle_type_code_5
0,2019-10-21T00:00:00.000,9:30,QUEENS,11416.0,40.683453,-73.855606,POINT (-73.855606 40.683453),ROCKAWAY BOULEVARD,97 AVENUE,NaN,...,Unspecified,NaN,NaN,NaN,4226874,Station Wagon/Sport Utility Vehicle,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN
2,2019-10-04T00:00:00.000,21:30,BRONX,10451.0,40.815437,-73.924000,POINT (-73.924 40.815437),MORRIS AVENUE,EAST 144 STREET,NaN,...,Unspecified,NaN,NaN,NaN,4217834,Taxi,Bike,NaN,NaN,NaN
4,2019-10-29T00:00:00.000,8:46,BRONX,10457.0,40.840420,-73.910920,POINT (-73.91092 40.84042),NaN,NaN,240 EAST 172 STREET,...,Unspecified,NaN,NaN,NaN,4231692,Sedan,Sedan,NaN,NaN,NaN
7,2019-10-13T00:00:00.000,12:50,BRONX,10455.0,40.814934,-73.914960,POINT (-73.91496 40.814934),EAST 149 STREET,BROOK AVENUE,NaN,...,Driver Inattention/Distraction,NaN,NaN,NaN,4222689,Sedan,Sedan,NaN,NaN,NaN
9,2019-10-24T00:00:00.000,7:05,QUEENS,11375.0,40.715073,-73.827220,POINT (-73.82722 40.715073),126 STREET,UNION TURNPIKE,NaN,...,Driver Inattention/Distraction,NaN,NaN,NaN,4228591,Sedan,Pick-up Truck,NaN,NaN,NaN
10,2019-10-22T00:00:00.000,17:00,QUEENS,11423.0,40.720352,-73.763240,POINT (-73.76324 40.720352),NaN,NaN,198-63 FOOTHILL AVENUE,...,NaN,NaN,NaN,NaN,4227760,Sedan,NaN,NaN,NaN,NaN
11,2019-10-18T00:00:00.000,14:20,QUEENS,11385.0,40.695070,-73.903160,POINT (-73.90316 40.69507),NaN,NaN,1060 WYCKOFF AVENUE,...,NaN,NaN,NaN,NaN,4225875,Box Truck,NaN,NaN,NaN,NaN
13,2019-10-16T00:00:00.000,18:45,QUEENS,11422.0,40.665245,-73.737090,POINT (-73.73709 40.665245),140 AVENUE,SOUTH CONDUIT AVENUE,NaN,...,Unspecified,NaN,NaN,NaN,4224224,Sedan,Bus,NaN,NaN,NaN
18,2019-10-04T00:00:00.000,0:33,QUEENS,11433.0,40.699990,-73.783900,POINT (-73.7839 40.69999),NaN,NaN,107-09 172 STREET,...,Unspecified,NaN,NaN,NaN,4219444,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN,NaN
21,2019-10-16T00:00:00.000,23:30,BRONX,10461.0,40.856842,-73.859150,POINT (-73.85915 40.856842),LURTING AVENUE,PELHAM PARKWAY SOUTH,NaN,...,NaN,NaN,NaN,NaN,4224429,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN,NaN
28,2019-10-09T00:00:00.000,17:38,QUEENS,11432.0,40.714542,-73.781240,POINT (-73.78124 40.714542),AVON STREET,WEXFORD TERRACE,NaN,...,Unspecified,NaN,NaN,NaN,4220543,Motorcycle,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN
31,2019-10-15T00:00:00.000,0:00,BRONX,10469.0,40.877720,-73.841790,POINT (-73.84179 40.87772),WICKHAM AVENUE,TILLOTSON AVENUE,NaN,...,Unspecified,NaN,NaN,NaN,4223384,Sedan,NaN,NaN,NaN,NaN
33,2019-10-18T00:00:00.000,16:54,QUEENS,11419.0,40.684383,-73.823265,POINT (-73.823265 40.684383),107 AVENUE,LEFFERTS BOULEVARD,NaN,...,Unspecified,NaN,NaN,NaN,4226733,Sedan,NaN,NaN,NaN,NaN
36,2019-10-04T00:00:00.000,8:16,QUEENS,11418.0,40.704680,-73.835900,POINT (-73.8359 40.70468),NaN,NaN,83-67 116 STREET,...,Unspecified,NaN,NaN,NaN,4217685,Bus,Sedan,NaN,NaN,NaN
37,2019-10-04T00:00:00.000,19:41,QUEENS,11420.0,40.682537,-73.807160,POINT (-73.80716 40.682537),LINDEN BOULEVARD,135 STREET,NaN,...,Unspecified,NaN,NaN,NaN,4217706,Sedan,Taxi,NaN,NaN,NaN
39,2019-10-22T00:00:00.000,2:12,QUEENS,11412.0,40.691210,-73.752960,POINT (-73.75296 40.69121),119 AVENUE,198 STREET,NaN,...,Unspecified,NaN,NaN,NaN,4227583,Sedan,Sedan,NaN,NaN,NaN
45,2019-10-30T00:00:00.000,8:00,QUEENS,11354.0,40.766075,-73.831240,POINT (-73.83124 40.766075),NaN,NaN,34-25 LINDEN PLACE,...,Unspecified,NaN,NaN,NaN,4232174,Sedan,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN
51,2019-10-02T00:00:00.000,14:00,QUEENS,11366.0,40.732830,-73.782875,POINT (-73.782875 40.73283),NaN,NaN,73-11 188 STREET,...,Unspecified,NaN,NaN,NaN,4216484,Sedan,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN
53,2019-10-03T00:00:00.000,12:30,QUEENS,11375.0,40.724400,-73.849810,POINT (-73.84981 40.7244),QUEENS BOULEVARD,68 DRIVE,NaN,...,Unspecified,NaN,NaN,NaN,4217118,Sedan,Bus,NaN,NaN,NaN
54,2019-10-03T00:00:00.000,16:20,QUEENS,11435.0,40.698917,-73.806900,POINT (-73.8069 40.698917),NaN,NaN,94-06 SUTPHIN BOULEVARD,...,Unspecified,NaN,NaN,NaN,4217132,Station Wagon/Sport Utility Vehicle,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN
59,2019-10-14T00:00:00.000,19:45,BRONX,10468.0,40.859303,-73.898840,POINT (-73.89884 40.859303),EAST 184 STREET,GRAND CONCOURSE,NaN,...,Other Vehicular,NaN,NaN,NaN,4223190,Station Wagon/Sport Utility Vehicle,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN
60,2019-10-28T00:00:00.000,14:00,QUEENS,11422.0,40.667220,-73.737050,POINT (-73.73705 40.66722),NaN,NaN,138-69 FRANCIS LEWIS BOULEVARD,...,Unspecified,NaN,NaN,NaN,4231094,Box Truck,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN
64,2019-10-18T00:00:00.000,10:30,BRONX,10456.0,40.832573,-73.910520,POINT (-73.91052 40.832573),EAST 168 STREET,CLAY AVENUE,NaN,...,NaN,NaN,NaN,NaN,4225605,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN,NaN
69,2019-10-02T00:00:00.000,11:18,QUEENS,11434.0,40.666637,-73.781490,POINT (-73.78149 40.666637),155 STREET,SOUTH CONDUIT AVENUE,NaN,...,Unspecified,NaN,NaN,NaN,4216996,Station Wagon/Sport Utility Vehicle,Sedan,NaN,NaN,NaN
74,2019-10-30T00:00:00.000,16:42,QUEENS,11374.0,40.719975,-73.865240,POINT (-73.86524 40.719975),WOODHAVEN BOULEVARD,65 AVENUE,NaN,...,Driver Inattention/Distraction,NaN,NaN,NaN,4232278,Sedan,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN
76,2019-10-09T00:00:00.000,21:12,BRONX,10466.0,40.894115,-73.846040,POINT (-73.84604 40.894115),NaN,NaN,4170 GRACE AVENUE,...,Unspecified,Unspecified,Unspecified,NaN,4220815,Sedan,Sedan,Sedan,Sedan,NaN
79,2019-10-04T00:00:00.000,12:00,BRONX,10451.0,40.818810,-73.928280,POINT (-73.92828 40.81881),EAST 149 STREET,WALTON AVENUE,NaN,...,Unspecified,NaN,NaN,NaN,4217832,Sedan,Sedan,NaN,NaN,NaN
85,2019-10-25T00:00:00.000,14:45,BRONX,10466.0,40.894660,-73.861370,POINT (-73.86137 40.89466),BRONX BOULEVARD,EAST 233 STREET,NaN,...,Unspecified,NaN,NaN,NaN,4229298,Sedan,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN
89,2019-10-13T00:00:00.000,14:14,BRONX,10462.0,40.835460,-73.856330,POINT (-73.85633 40.83546),NaN,NaN,2062 MCGRAW AVENUE,...,Unspecified,NaN,NaN,NaN,4222777,Station Wagon/Sport Utility Vehicle,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN
94,2019-10-16T00:00:00.000,19:00,QUEENS,11368.0,40.740585,-73.858536,POINT (-73.858536 40.740585),NaN,NaN,54-23 102 STREET,...,Unspecified,NaN,NaN,NaN,4224348,Sedan,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
903,2019-10-26T00:00:00.000,3:02,QUEENS,11435.0,40.694065,-73.801420,POINT (-73.80142 40.694065),SUTPHIN BOULEVARD,107 AVENUE,NaN,...,Unspecified,NaN,NaN,NaN,4239074,Sedan,Sedan,NaN,NaN,NaN
905,2019-10-05T00:00:00.000,16:55,BRONX,10475.0,40.868790,-73.831680,POINT (-73.83168 40.86879),BARTOW AVENUE,BAYCHESTER AVENUE,NaN,...,Unspecified,NaN,NaN,NaN,4218757,Sedan,PK,NaN,NaN,NaN
906,2019-10-19T00:00:00.000,12:00,BRONX,10458.0,40.856810,-73.898180,POINT (-73.89818 40.85681),VALENTINE AVENUE,EAST 183 STREET,NaN,...,Unspecified,NaN,NaN,NaN,4225984,Box Truck,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN
907,2019-10-28T00:00:00.000,8:00,QUEENS,11432.0,40.711823,-73.787860,POINT (-73.78786 40.711823),HILLSIDE AVENUE,175 STREET,NaN,...,Unspecified,NaN,NaN,NaN,4231048,Bus,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN
910,2019-10-06T00:00:00.000,3:49,QUEENS,11385.0,40.696740,-73.900510,POINT (-73.90051 40.69674),CYPRESS AVENUE,SUMMERFIELD AVENUE,NaN,...,Unspecified,NaN,NaN,NaN,4218276,Station Wagon/Sport Utility Vehicle,Box Truck,NaN,NaN,NaN
911,2019-10-17T00:00:00.000,8:00,BRONX,10466.0,40.890015,-73.851740,POINT (-73.85174 40.890015),NaN,NaN,911 EAST 231 STREET,...,Unspecified,NaN,NaN,NaN,4224603,Station Wagon/Sport Utility Vehicle,Sedan,NaN,NaN,NaN
915,2019-10-21T00:00:00.000,8:50,QUEENS,11419.0,40.687668,-73.811700,POINT (-73.8117 40.687668),107 AVENUE,133 STREET,NaN,...,Failure to Yield Right-of-Way,NaN,NaN,NaN,4227249,Station Wagon/Sport Utility Vehicle,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN
917,2019-10-11T00:00:00.000,8:10,BRONX,10455.0,40.815845,-73.895440,POINT (-73.89544 40.815845),LONGWOOD AVENUE,BRUCKNER BOULEVARD,NaN,...,Unspecified,NaN,NaN,NaN,4222010,Station Wagon/Sport Utility Vehicle,Box Truck,NaN,NaN,NaN
918,2019-10-12T00:00:00.000,1:00,QUEENS,11429.0,40.705223,-73.746260,POINT (-73.74626 40.705223),NaN,NaN,209-31 112 AVENUE,...,Unspecified,NaN,NaN,NaN,4221790,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN,NaN
920,2019-10-03T00:00:00.000,21:00,QUEENS,11422.0,40.678417,-73.729225,POINT (-73.729225 40.678417),BROOKVILLE BOULEVARD,130 AVENUE,NaN,...,Unspecified,NaN,NaN,NaN,4217259,Sedan,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN
925,2019-10-08T00:00:00.000,8:30,BRONX,10461.0,40.851460,-73.848206,POINT (-73.848206 40.85146),NaN,NaN,1731 SEMINOLE AVENUE,...,Driver Inexperience,NaN,NaN,NaN,4220222,Station Wagon/Sport Utility Vehicle,Sedan,NaN,NaN,NaN
926,2019-09-09T00:00:00.000,11:10,BRONX,10453.0,40.847680,-73.912370,POINT (-73.91237 40.84768),JEROME AVENUE,EAST 175 STREET,NaN,...,NaN,NaN,NaN,NaN,4203022,Sedan,NaN,NaN,NaN,NaN
929,2019-10-19T00:00:00.000,21:22,BRONX,10463.0,40.885180,-73.901024,POINT (-73.901024 40.88518),KINGSBRIDGE AVENUE,WEST 238 STREET,NaN,...,NaN,NaN,NaN,NaN,4226102,Sedan,NaN,NaN,NaN,NaN
936,2019-10-21T00:00:00.000,19:13,BRONX,10453.0,40.861862,-73.912820,POINT (-73.91282 40.861862),WEST FORDHAM ROAD,MAJOR DEEGAN EXPRESSWAY,NaN,...,Unspecified,NaN,NaN,NaN,4227274,Station Wagon/Sport Utility Vehicle,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN
937,2019-10-17T00:00:00.000,9:07,BRONX,10469.0,40.874382,-73.857010,POINT (-73.85701 40.874382),NaN,NaN,1027 EAST GUN HILL ROAD,...,Unspecified,NaN,NaN,NaN,4225371,Tractor Truck Diesel,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN
938,2019-10-21T00:00:00.000,12:15,BRONX,10458.0,40.859875,-73.893230,POINT (-73.89323 40.859875),WEBSTER AVENUE,EAST 188 STREET,NaN,...,Driver Inattention/Distraction,NaN,NaN,NaN,4227334,Sedan,Pick-up Truck,NaN,NaN,NaN
943,2019-10-05T00:00:00.000,16:30,QUEENS,11378.0,40.722600,-73.904570,POINT (-73.90457 40.7226),61 STREET,57 ROAD,NaN,...,Unspecified,NaN,NaN,NaN,4218270,Sedan,Sedan,NaN,NaN,NaN
951,2019-10-13T00:00:00.000,20:00,QUEENS,11426.0,40.725950,-73.721480,POINT (-73.72148 40.72595),91 AVENUE,247 STREET,NaN,...,Unspecified,NaN,NaN,NaN,4223213,Station Wagon/Sport Utility Vehicle,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN
953,2019-10-25T00:00:00.000,16:35,QUEENS,11692.0,40.597660,-73.785410,POINT (-73.78541 40.59766),NaN,NaN,54-81 ALMEDA AVENUE,...,Unspecified,NaN,NaN,NaN,4233109,Sedan,NaN,NaN,NaN,NaN
955,2019-10-22T00:00:00.000,19:00,QUEENS,11361.0,40.768826,-73.763620,POINT (-73.76362 40.768826),221 STREET,37 AVENUE,NaN,...,Passing or Lane Usage Improper,NaN,NaN,NaN,4227658,Station Wagon/Sport Utility Vehicle,Sedan,NaN,NaN,NaN
957,2019-10-04T00:00:00.000,6:00,QUEENS,11356.0,40.785660,-73.855095,POINT (-73.855095 40.78566),14 AVENUE,112 STREET,NaN,...,Unspecified,NaN,NaN,NaN,4220901,Sedan,NaN,NaN,NaN,NaN
959,2019-10-07T00:00:00.000,7:44,QUEENS,11417.0,40.676395,-73.850900,POINT (-73.8509 40.676395),NaN,NaN,109-08 86 STREET,...,Unspecified,NaN,NaN,NaN,4219372,Sedan,Bus,NaN,NaN,NaN
969,2019-10-11T00:00:00.000,14:00,QUEENS,11004.0,40.752777,-73.707430,POINT (-73.70743 40.752777),NaN,NaN,269-01 76 AVENUE,...,NaN,NaN,NaN,NaN,4221718,Sedan,NaN,NaN,NaN,NaN
972,2019-10-11T00:00:00.000,19:48,QUEENS,11414.0,40.667900,-73.842040,POINT (-73.84204 40.6679),CROSS BAY BOULEVARD,153 AVENUE,NaN,...,Unspecified,NaN,NaN,NaN,4221679,Bike,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN
977,2019-10-18T00:00:00.000,20:30,BRONX,10457.0,40.845966,-73.892240,POINT (-73.89224 40.845966),EAST TREMONT AVENUE,HUGHES AVENUE,NaN,...,Unspecified,NaN,NaN,NaN,4226697,Taxi,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN
984,2019-10-18T00:00:00.000,11:16,BRONX,10462.0,40.848824,-73.861710,POINT (-73.86171 40.848824),BRONXDALE AVENUE,MULINER AVENUE,NaN,...,Unspecified,NaN,NaN,NaN,4225337,Van,Sedan,NaN,NaN,NaN
987,2019-10-08T00:00:00.000,9:30,BRONX,10461.0,40.853046,-73.853520,POINT (-73.85352 40.853046),NaN,NaN,1937 WILLIAMSBRIDGE ROAD,...,Unspecified,NaN,NaN,NaN,4223967,Sedan,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN
992,2019-10-10T00:00:00.000,8:00,QUEENS,11412.0,40.701412,-73.768390,POINT (-73.76839 40.701412),HANNIBAL STREET,HILBURN AVENUE,NaN,...,Unspecified,NaN,NaN,NaN,4220935,Sedan,Sedan,NaN,NaN,NaN
994,2019-10-25T00:00:00.000,18:36,QUEENS,11385.0,40.700512,-73.899124,POINT (-73.899124 40.700512),MYRTLE AVENUE,STEPHEN STREET,NaN,...,Unspecified,NaN,NaN,NaN,4230594,Pick-up Truck,NaN,NaN,NaN,NaN
998,2019-10-30T00:00:00.000,8:23,QUEENS,11368.0,40.747740,-73.857750,POINT (-73.85775 40.74774),NaN,NaN,107-98 45 AVENUE,...,Unspecified,NaN,NaN,NaN,4232379,Station Wagon/Sport Utility Vehicle,Ambulance,NaN,NaN,NaN

In [17]:
df_queen=df[condicion_1]

In [18]:
df_queen['borough'].value_counts()

QUEENS    213
Name: borough, dtype: int64

In [19]:
df.groupby(['borough'])['collision_id'].nunique()

borough
BRONX             97
BROOKLYN         183
MANHATTAN        114
QUEENS           213
STATEN ISLAND     13
Name: collision_id, dtype: int64

### Trabajo con fechas